project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - sample_final.qmd
    - sample_midterm.qmd
  resources:
    - CNAME
    - Chapter*.pdf
    - .nojekyll

               
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: "BUSI 521 Asset Pricing / ECON 505 Financial Economics I"
    file: index.qmd
    right:
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd  
      - text: Solutions
        url: https://github.com/kerryback/busi521/tree/main/solutions
      - text: Sample Midterm
        file: sample_midterm.qmd
      - text: Sample Final
        file: sample_final.qmd

        
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    
   



