project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - sample_final.qmd
    - sample_midterm.qmd
    - solutions.qmd
  resources:
    - CNAME
    - Chapter*.pdf
    - .nojekyll
    - room_schedule.pdf
    - solutions/*.pdf

               
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: "BUSI 521 Asset Pricing / ECON 505 Financial Economics I"
    file: index.qmd
    right:
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd  
      - text: Solutions
        file: solutions.qmd
      - text: Room Schedule
        file: room_schedule.pdf 
      - text: NotebookLM
        url: https://notebooklm.google.com/notebook/5ebfd59c-0deb-46da-a80a-85c66ea683b6
      - text: Sample Midterm
        file: sample_midterm.qmd
      - text: Sample Final
        file: sample_final.qmd

        
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    
   



