project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
    - assignments.qmd
    - sample_final.qmd
    - podcasts.qmd
    - sample_midterm.qmd
    - sample_final.qmd
               
website:
  title: ""
  search: false  
  navbar:
    search: false
    title: "BUSI 521 / ECON 505: ASSET PRICING / FIN ECON I"
    file: index.qmd
    right:
      - text: Slides
        file: slides.qmd
      - text: Assignments
        file: assignments.qmd  
      - text: Podcasts 
        file: podcasts.qmd 
        
format:
  html:
    theme:
      light: flatly
      dark: superhero
    link-external-newwindow: true
    
   



